# Site
title:              RMCD
bio:                'Oh, hello there!'
description:        "Naturally curious. A bit of projects, tech, science, sports, FOSS, and a lot of everything else"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.jpg'
background:         'assets/img/background.jpg'
tiled_bg:           false   # True to tile background image, otherwise stays covered
locale:             en_US
url:                https://r-m-c-d.github.io/
rss:                true
author:
  medium: '@r_mcd'

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
#disqus_shortname:   

#Social
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
twitter:            rmcd0
#facebook:           username
github-url:         https://github.com/r-m-c-d
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:           username
medium:            '@r_mcd'
#email:              
#youtube:           https://www.youtube.com/channel/UCsv0AE2pnyu2D2qTj4DPulw?
#youtube-channel:   channel


# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
